### ISSUE TITLE
GET and POST method is always enabled for CORS?

### ISSUE THREAD

**Issue by ChengTian** [aspnet/CORS#12]
Create a simple MVC web app with the following code
```
services.ConfigureCors(options =>
{
    options.AddPolicy(
        "AllowMyMethodRequest",
        builder =>
        {
            builder.AllowAnyOrigin()
                    .WithMethods("MYMETHOD");
        });
}
```
as the only CORS-related configuration.
Then apply `[EnableCors("AllowMyMethodRequest")]` to an action in your controller and try accessing view of that action. Here are the methods I used and corresponding results:
(1) GET: succeeds (why?)
(2) POST: succeeds (why?)
(3) HEAD: fails (expected)
(4) MYMETHOD: succeeds (expected)

**Comment by harshgMSFT** [comment]
Here is what I saw, since you are using a local scriptiong source, the browser is sending Origin header as null 
something like
```
HEAD http://localhost:6960/Home/Action HTTP/1.1
Host: localhost:6960
Connection: keep-alive
Content-Length: 0
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
Origin: null
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

The response is 
```
HTTP/1.1 200 OK
Content-Length: 127
Content-Type: text/plain; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Server: Microsoft-IIS/10.0
Access-Control-Allow-Origin: *
X-SourceFiles: =?UTF-8?B?ZDpcQ29yc0RlYnVnXHNyY1xDb3JzRGVidWdcd3d3cm9vdFxIb21lXEFjdGlvbg==?=
X-Powered-By: ASP.NET
Date: Fri, 03 Apr 2015 04:40:26 GMT

```
Now the reason why we get a Access-Control-Allow-Origin: * is because the presence of ORIGIN causes 
`var origin = context.Request.Headers.Get(CorsConstants.Origin);`
to return an empty value. 

The reason why you do not see a content in response is because for Head, you only get headers and not the content.
"When you send a HEAD request, it means that you are only interested in the response code and the HTTP headers, not the document itself."

The behavior is as expected. Please let me know if you are seeing a different behavior.

**Comment by ChengTian** [comment]
I am seeing the same behavior. Thanks for the explanation.

Add more clarification from @harshgMSFT :
When `AllowAnyOrigin()` is used, GET, POST and HEAD methods should be automatically enabled. That's why GET and POST should work in the repro steps.

**Comment by harshgMSFT** [comment]
>When AllowAnyOrigin() is used, GET, POST and HEAD methods should be automatically enabled. 

This statement is not true. 
For simple requests, the only thing that matters (in this context)  is whether the value in the ORIGIN header matches. It does not matter for which HTTP verb the simple request is for.
