### ISSUE TITLE
EnableCorsAttribute has a way to set policy name via the ctor and the property

### ISSUE THREAD

**Issue by pranavkm** [aspnet/CORS#121]
Seems strange since both things apply to the same thing.

![image](https://user-images.githubusercontent.com/174281/28689060-19b66104-72c9-11e7-9da4-5cb3e28c3037.png)

**Comment by pranavkm** [comment]
We could make the setter `EditorBrowseable(Never)` just so that it's less confusing for future users and does not break copy-paste etc

**Comment by Eilon** [comment]
Looks like it's settable because that comes from the interface: https://github.com/aspnet/CORS/blob/dev/src/Microsoft.AspNetCore.Cors/Infrastructure/IEnableCorsAttribute.cs#L14

Though we could have easily hidden the setter in a variety of ways.

But... this seems low value; I doubt it's really confusing to anyone.
