### ISSUE TITLE
CorsMiddleware not rejecting invalid requests

### ISSUE THREAD

**Issue by bungeemonkee** [aspnet/CORS#125]
I've setup cors per the documentation and am able to verify with the debugger that the correct policy is being used by the middleware and that the middleware is being executed. However any invalid request (disallowed origin, disallowed method, authorization when there shouldn't be, etc.) is not being rejected by the middleware. It appreas to respond to valid options preflights and nothing else (invalid preflights are ignored as well).

I have also tried adding CorsAuthorizationFilterFactory to the global mvc filters list and it appears to do nothing.

How can I globally reject any requests that violate my cors policy?

**Comment by Eilon** [comment]
@kichalla can you take a look?

**Comment by Eilon** [comment]
Please discuss results with me directly.

**Comment by kichalla** [comment]
@bungeemonkee Could you share an example of where you have seen it not working? I tried few scenarios using the [sample](https://github.com/aspnet/CORS/tree/dev/samples) in this repo and invalid requests like disallowed origin, disallowed method etc. and they are working as expected.
Also which version of Cors middleware are you using?

**Comment by bungeemonkee** [comment]
Sorry for the delayed response.

I'm using version 2.0.0 though this problem appears to have been around since the 1.X branch and I simply didn't notice. I have set the project up per the example. The only substantial difference being that there is swagger, swagger ui, and authentication middleware between the cors middleware and the mvc routing middleware.

Having dug through the cors project code I suspect that the issue is that after the middleware applies the policy on line 96 (https://github.com/aspnet/CORS/blob/51aecc2c180e4232dfd9fdd5a11e6ca6688cb996/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsMiddleware.cs#L96) it does not return if the result of the evaluation (one line above) is failure. This means that any requests that are not a preflight request will continue to be processed by other middleware even if they are invalid.

Once I saw that I attempted to add the CorsAuthorizationFilterFactory to the global filters thinking that was the intended solution. I assumed that the the filter was supposed to intercept these invalid requests that fell through the middleware and reject them.

I think the fix is to add a condition after the preflight condition is processed - at line 110 (https://github.com/aspnet/CORS/blob/51aecc2c180e4232dfd9fdd5a11e6ca6688cb996/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsMiddleware.cs#L110) - to return when the result of evaluating the policy is failure. But if you are sure that it works in its current state I must be wrong.

Honestly, I don't see how this could have ever worked in this state so I assume there is something I'm missing. If you could explain what code leads to the rejection of requests that violate any cors rules maybe I could figure out what I'm doing wrong?

**Comment by kichalla** [comment]
@bungeemonkee Yes, your observation is correct but this should not be an issue in real scenarios.

Examples: 
- If a webpage is trying to make a CORS request with PUT verb, then the browser would kick off a Preflight request. Upon receiving the preflight request the server application would reject it based on the policy failure and since this request is rejected by the server, the browser would not make the actual request.
- If a webpage is trying to make a CORS request with GET verb, then the browser would kick off the actual request(not preflight as its considered a 'Simple Method' by CORS spec). Yes, in this case the request would go through the rest of the pipeline even though the CORS policy fails, but on the other hand GET requests are supposed to be idempotent and so they shouldn't cause any side effects.

**Comment by bungeemonkee** [comment]
@kichalla OK, so if I set up a CORS policy to restrict by domain (the value of the "Origin" header) this will - by design - be ignored for Ajax requests that are GET? This seems off. Even though I'm using HSTS to ensure https and using oauth2 tokens to restrict access to only properly authenticated parties I'd really like the extra security of knowing that if a hole is found either in the https or the oauth that CORS is going to reject even GET requests from invalid domains. It simply adds another layer to the onion.

If this isn't the use case for CORS I'm curious what the intent is.

Perhaps a configuration switch to add CORS validation to even 'Simple Methods'? Essentially make the default behavior spec compliant but give jerks like me an option to deviate from it. If you approve of that approach I'd be glad to knock together a PR with the actual work in it.

**Comment by Eilon** [comment]
cc @blowdart 

@bungeemonkee I think the issue with "protecting" a GET request with CORS is that you don't need CORS to make GET requests (or POSTs). A "malicious" site could just create a simple form:

```html
<form id="form1" method="get/post" action="http://innocent-site.example.com/some-page">
    <input type="hidden" value="Danger!" />
    ... more stuff here
</form>
<script>
    document.getElementById('form1').submit();
</script>
```

And BAM, the get/post goes through. (I didn't actually test my code, but in general it'll work fine, minus any mistakes I've made.)

So I don't think CORS is meant to add any extra protection here because there's already a much simpler "classical" approach to attacking a site.

To more seriously protect a site in this case I recommend using anti-forgery, which protects against cross-site request forgery (XSRF/CSRF).

Here's our ASP.NET Core doc on using anti-forgery: https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery
