### ISSUE TITLE
Cors does not appear if the application crash

### ISSUE THREAD

**Issue by Kuqd** [aspnet/CORS#86]
When your application crash (500 Internal Error), cors response header are not present.

I think it should because the error on the front is therefore misleading.

**request headers:** 

Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-GB,en;q=0.8,en-US;q=0.6,fr;q=0.4
Connection:keep-alive
Host:localhost:5000
Origin:http://localhost:3000
Referer:http://localhost:3000/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
X-FirePHP-Version:0.0.6

**response headers :** 

Content-Type:text/html; charset=utf-8
Date:Fri, 02 Sep 2016 15:03:12 GMT
Server:Kestrel
Transfer-Encoding:chunked

Cors is active and works for successful requests.

**Comment by Eilon** [comment]
I suspect you're running into the same issue as https://github.com/aspnet/CORS/issues/46, which we closed as by-design.

If you're looking to do your own more advanced errors, you can certainly return any response you like, with any headers you like. But I believe that out-of-the-box it defaults to not showing the error page because it is either typically of no value to the caller, or it is potentially dangerous to have the caller see it.

**Comment by Kuqd** [comment]
Alright ! Thanks
