### ISSUE TITLE
OPTIONS requests receiving 404 when routes have HTTP method constraints

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/CORS#98]
My `Startup.cs` contains the following:

```
            services.AddCors(options => options
                .AddPolicy("TrustedHosts", builder => builder
                    .AllowCredentials()
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .WithOrigins(Configuration.TrustedHosts().ToArray())));
```

I have my own tools for registering routes, however I've noticed an interesting/odd behaviour when using controller annotation for CORS.  I believe it boils down to this:

```
if (httpMethod != null)
    constraints.Add("httpMethod", new HttpMethodRouteConstraint(httpMethod));
```

What I think is happening is the preflight only works when I remove any HTTP method constraint from the route.

I'm not sure if that's just a limitation of using annotations, in which case I might see about providing a way to register CORS policies against routes in my utilities.  But this is definitely a strange and unexpected side effect of using the controller annotations.

**Comment by Eilon** [comment]
Routing runs before MVC, so if the route has a constraint that doesn't allow an `OPTIONS` request, then MVC will never see the request, so its CORS logic won't run. The result is that unless some other middleware can handle that request, the server will return a 404.

You could instead consider using the CorsMiddleware (that's in this repo) because it can be registered before MVC (and thus Routing). However, the policy definition isn't as granular as with MVC because you can't use the `[EnableCors]` attributes on the actions.

So, in this particular scenario, it might be good to set up the HttpMethodRouteConstraint to allow both the desired "regular" HTTP method, plus also the OPTIONS HTTP method. You can pass in multiple allowed HTTP methods in the constructor of the constraint: https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Constraints/HttpMethodRouteConstraint.cs#L21

**Comment by atrauzzi** [comment]
Thanks! This approach sounds good!

**Comment by jeremysimmons** [comment]
@Eilon first, sorry to necro this post.

This *really* violated the principle of least surprise for me. I was expecting the [EnableCors("Policy")] on my controller to WORK, regardless of the fact that I had used [HttpPost("Route/Template/")] on my controller's action method. At minimum, the [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.0#enabling-cors-in-mvc) does not make it abundantly clear that this is a tar-trap. At best, it should "just work"(tm).
I'd be happy to submit a minimal reproduction web project if required.

**Comment by Rick-Anderson** [comment]
@jeremysimmons can you propose changes to the doc or submit a PR for that?
